N_CHANNELS: 8
N_SUBCHANNELS: 8
N_DATAPOINTS: 1
MAX_SONG_DURATION: 900
SR: 22050
WINDOW_SIZE: 4410 
MAX_FREQUENCY: 6000
MATCH_THRESHOLD: 0.5
SONGS_URL: "https://gist.githubusercontent.com/keune/0de5c7fb669f7b682874/raw/4aabd7282ee6b58ff886af50489cbcc6c4bd1faf/RollingStone%20Top%20500%20Song"

